[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["ajgoodm <aarongoodm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.4.9"
lazy_static = "1.2.0"
regex = "1.5"